//! Zotero library access.
//!
//! Four sources, presented behind one interface, degrading rather than failing.
//! The highest available source is the live one:
//!
//! | Priority | Source | Requires |
//! |---|---|---|
//! | 1 | Better BibTeX JSON-RPC | Zotero running + BBT |
//! | 2 | Zotero 7 local API | Zotero running |
//! | 3 | Watched exported `.bib` | An export exists |
//! | 4 | Read-only copy of `zotero.sqlite` | Zotero data directory found |
//!
//! **The active source is always reported to the user.** Silently degrading to a
//! stale library is a correctness problem in a citation tool, not a graceful
//! fallback.
//!
//! Note also what this crate is *not*: the project `.bib` is the compile-time
//! source of truth, and nothing here is required to build a document.
//!
//! See [ADR-0008](https://github.com/GeneralPawz/yaz/blob/main/docs/adr/0008-zotero-integration.md).

//! # Constructing the HTTP client
//!
//! Use [`yaz_core::net::http_client`], never `reqwest::Client::new`. The trust
//! policy in
//! [ADR-0019](https://github.com/GeneralPawz/yaz/blob/main/docs/adr/0019-tls-trust-store.md)
//! has one implementation on purpose: a client built here with reqwest's
//! defaults would trust a different set of roots than the rest of the
//! application, and the difference would only show up on a user's network.

#![deny(missing_docs)]
#![deny(unsafe_code)]
#![warn(clippy::all)]

pub mod bib;
pub mod datadir;
pub mod error;
pub mod launch;
pub mod library;
pub mod local_api;
pub mod model;
pub mod sqlite;

pub use error::{Error, Result};
pub use library::{Config, Library};
pub use model::{Annotation, AnnotationKind, Item};

/// Which source is currently serving library queries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActiveSource {
    /// Better BibTeX JSON-RPC. Full capability, including stable citation keys.
    BetterBibTeX,
    /// Zotero's own local API. Live, but citation keys are generated by us.
    LocalApi,
    /// A watched `.bib` export. Offline; as current as the last export.
    ExportedBib,
    /// A read-only copy of the Zotero database. Offline.
    Sqlite,
    /// No source available.
    None,
}

impl ActiveSource {
    /// Message key describing this source in the connection indicator.
    pub fn status_key(&self) -> &'static str {
        match self {
            ActiveSource::BetterBibTeX => "zotero-source-better-bibtex",
            ActiveSource::LocalApi => "zotero-source-local-api",
            ActiveSource::ExportedBib => "zotero-source-exported-bib",
            ActiveSource::Sqlite => "zotero-source-sqlite",
            ActiveSource::None => "zotero-source-none",
        }
    }

    /// Whether this source reflects the library as it is right now.
    pub fn is_live(&self) -> bool {
        matches!(self, ActiveSource::BetterBibTeX | ActiveSource::LocalApi)
    }
}

// TODO(phase-5): source probing and selection, search, citation key resolution,
// attachment path resolution, sqlite schema version gating.
