# en-US is the source of truth for message keys. Other locales are translations
# of this file; a key missing elsewhere falls back through the locale chain
# (de-AT → de → en-US) rather than rendering a raw key.
#
# ICU/Fluent so that plurals and gender work in the languages that need them —
# a naïve "{count} items" is wrong in Polish, Russian and Arabic.
#
# See docs/adr/0011-localisation.md

## Application

app-name = yaz
app-tagline = Turn your ideas and sources into papers.

## Filesystem errors — keys come from yaz-core::Error::message_key()

error-fs-not-found = Could not find { $path }.
error-mcp-listen = The agent server could not start: { $detail }
error-plugin-manifest = That folder has a manifest.json that could not be read as a plugin.
error-plugin-repository = That plugin names a repository yaz cannot make sense of: { $detail }
error-plugin-update-check = The plugin's repository could not be reached: { $detail }
error-fs-outside-root = { $path } is outside { $root }, which this operation is limited to.
error-fs-undecodable = Could not read { $path } as text. It may be a binary file or use an unsupported encoding.
error-fs-conflicting-write = { $path } was changed outside yaz since you opened it. Saving now would discard those changes.
error-fs-io = Something went wrong reading or writing { $path }.

## Compilation

compile-run = Compile
compile-running = Compiling…
compile-succeeded = Compiled in { $seconds }s.
compile-failed = Compilation failed.
compile-diagnostics-count = { $count } error(s)
compile-diagnostics =
    { $count ->
        [one] 1 problem
       *[other] { $count } problems
    }
compile-engine-unavailable = This project is set to use { $engine }, which is not installed. Install a TeX distribution, or switch this project to the built-in Tectonic engine.

## Engines

settings-engine = Engine
settings-engine-help = Saved in yaz.toml, so co-authors compile the same way you do.
engine-tectonic-not-built = Not included in this build of yaz. It has to be compiled in — a setting cannot add it.
engine-system-not-installed = Not installed on this computer.
engine-unavailable-suffix = unavailable

## Zotero — keys come from yaz-zotero::ActiveSource::status_key()

zotero-source-better-bibtex = Zotero: connected via Better BibTeX
zotero-source-local-api = Zotero: connected
zotero-source-exported-bib = Zotero: offline — reading an exported .bib
zotero-source-sqlite = Zotero: offline — reading the library database
zotero-source-none = Zotero: not available
zotero-keys-generated = Citation keys are generated by yaz because Better BibTeX is not available. They may not match a collaborator's.

## Plugin capabilities — generated reference reads these; keys come from
## yaz-plugin::Capability::description_key()

capability-fs-project-description = Read and change files in this project.
capability-fs-read-description = Read files at a specific location outside this project.
capability-fs-write-description = Change files at a specific location outside this project.
capability-net-description = Connect to the internet, limited to { $hosts }.
capability-process-description = Run programs on your computer: { $binaries }.
capability-mcp-client-description = Talk to the tools you have connected: { $servers }.
capability-zotero-description = Read your Zotero library.
capability-obsidian-description = Read your Obsidian vault.
capability-clipboard-description = Read and change the clipboard.
capability-notifications-description = Show desktop notifications.
capability-shell-open-description = Open links and files with your other applications.

## Plugin management

plugin-install-title = Install { $name }?
plugin-install-capabilities = This plugin is asking for:
plugin-install-unreviewed = This plugin has not been reviewed by anyone. Only install plugins from authors you trust.
plugin-update-new-capabilities = { $name } is asking for permissions it did not have before. Review them before updating.
plugin-error = { $name } stopped working.
plugin-error-disable = Disable { $name }

## Workspace

workspace-open-project = Open folder…
workspace-no-project = No folder open yet.
workspace-no-files = No .tex files in this folder.
workspace-no-file-open = Choose a file to start writing.
workspace-entry = entry

## Editor

editor-mode-source = Source
editor-mode-visual = Visual
editor-vim-mode = Vim
editor-loading = Opening…

## PDF

pdf-empty = Compile to see your document here.
pdf-showing = Showing { $file } — not the compiled output

## Settings

settings-appearance = Appearance
settings-theme = Theme
settings-colour-mode = Appearance mode
settings-colour-mode-system = Match system
settings-colour-mode-light = Light
settings-colour-mode-dark = Dark
settings-interface-locale = Interface language
settings-document-locale = Document language
settings-document-locale-help = The language you are writing in. Separate from the interface language — it sets spellchecking, hyphenation and quotation marks.
settings-check-for-updates = Check for updates
settings-check-for-updates-help = Contacts GitHub to see whether a newer version exists.

## Pickers

picker-placeholder = Type to filter
picker-empty = Nothing to show
picker-loading = Loading…
picker-failed = Could not load the list

## Plugin runtime

plugin-error-not-loaded = That plugin is not loaded.
capability-error-not-declared = The plugin did not ask for permission to do that.
capability-error-not-granted = You have not granted the plugin permission to do that.
capability-error-out-of-scope = That is outside what the plugin is allowed to reach.

## Zotero — commands

zotero-command-cite = Cite from Zotero
zotero-command-cite-description = Search your Zotero library and insert a citation.
zotero-command-quote = Quote a highlight
zotero-command-quote-description = Insert a passage you highlighted in Zotero, with its citation.
zotero-command-reconnect = Reconnect to Zotero
zotero-command-reconnect-description = Look again for a running Zotero, then fall back to the offline library.

## Zotero — pickers

zotero-picker-source-title = Choose a source
zotero-picker-source-placeholder = Search by title or author
zotero-picker-source-empty = Nothing in your library matches
zotero-picker-passage-title = Choose a passage you marked
zotero-picker-passage-placeholder = Filter the passages
zotero-picker-passage-empty = No passages match
zotero-page-label = p. { $page }

## Zotero — notices

zotero-notice-no-editor = Open a document first.
zotero-notice-unavailable = No Zotero library was found at { $detail }.
zotero-notice-no-annotations = You have not marked anything in that source.
zotero-notice-no-quotable-annotations = That source has marks, but none of them are quotable text.
zotero-notice-generated-key = Inserted { $key }. That key was generated by yaz and may not match a collaborator's.

## Zotero — annotation kinds

zotero-annotation-highlight = Highlight
zotero-annotation-note = Note
zotero-annotation-image = Image
zotero-annotation-ink = Drawing
zotero-annotation-underline = Underline
zotero-annotation-other = Other

## Zotero — where the library was found

zotero-datadir-configured = the folder you chose
zotero-datadir-profile = the folder your Zotero profile points at
zotero-datadir-convention = the default Zotero folder

## Zotero — errors

zotero-error-no-library = No Zotero library was found.
zotero-error-unsupported-schema = This Zotero library was made by a newer Zotero than yaz understands, so it was not read.
zotero-error-unsupported-journal = This Zotero library stores recent changes separately, and yaz would only have read an out-of-date copy.
zotero-error-not-running = Zotero is not running.
zotero-error-unexpected-response = Zotero answered in a way yaz did not understand.
zotero-error-http = Could not reach Zotero.
zotero-error-database = Your Zotero library could not be read.
zotero-error-io = A file could not be read or written.
zotero-error-item-not-found = That item is no longer in your Zotero library.

## Zotero — the live connection

zotero-live-available = Connected to Zotero
zotero-live-not-running = Zotero is not running
zotero-live-api-disabled = Zotero is running, but its local API is switched off
zotero-live-api-disabled-help = Turn on "Allow other applications on this computer to communicate with Zotero" in Zotero's Advanced settings to read the library live.
zotero-live-unexpected = Zotero answered unexpectedly
zotero-demoted = The live connection failed, so the library is being read from a copy on disk.

## Menu bar

menu-file = File
menu-edit = Edit
menu-view = View
menu-tools = Tools
menu-help = Help

menu-file-open-folder = Open folder…
menu-file-save = Save
menu-file-compile = Compile
menu-file-close-project = Close project
menu-edit-undo = Undo
menu-edit-redo = Redo
menu-edit-find = Find…
menu-view-vim = Vim keys
menu-view-connections = Connections
menu-tools-engine = Typesetting engine
menu-help-documentation = Documentation
menu-help-report-issue = Report an issue
menu-help-about = About yaz
menu-not-implemented = That is not built yet.

## Connections

connections-title = Connections
connections-none = Nothing is configured yet.
connections-reconnect = Reconnect
connections-zotero = Zotero
connections-obsidian = Obsidian
connections-not-configured = Not configured
connections-reading-offline = Reading a copy of the library on disk
connections-source = Source: { $source }

## Window controls

window-minimise = Minimise
window-maximise = Maximise
window-restore = Restore
window-close = Close

## Settings

settings-title = Settings
settings-section-general = General
settings-section-engine = Typesetting
settings-section-connections = Connections
settings-group-editor = Editor
settings-group-typesetting = Engine
settings-vim-help = Modal editing in both source and visual mode.
settings-engine-no-project = Open a project to choose its engine. The choice is saved per project.

## Connections, continued

connections-unknown = Not connected yet
connections-connect-zotero = Connect to Zotero
connections-reconnect-zotero = Reconnect to Zotero
menu-tools-connections = Connections
menu-edit-settings = Settings…

## Workspace

workspace-close-tab = Close tab
workspace-tab-editor = Source
workspace-tab-pdf = PDF
menu-view-tabs = Tabs
menu-view-reset-layout = Reset layout

## File menu, continued

menu-file-open-recent = Open recent
menu-file-no-recent = No recent projects
compile-start = Compile

## Version control

vcs-title = Version history
vcs-enable = Start recording versions
vcs-disable = Stop recording versions
vcs-recording = Recording versions
vcs-not-recording = Not recording versions
vcs-unavailable = Version control is not available on this machine
vcs-backend-git = Git
vcs-backend-builtin = Built into yaz (not ready yet)
vcs-settings-backend = Records with
vcs-settings-backend-help = Git uses your own repository, so branches, remotes and hooks keep working. Switching version control off never deletes anything.
vcs-commit-with-message = Save a version with a message…
vcs-commit-placeholder = What changed, and why
vcs-commit-title = Save a version
vcs-commit-hint = Leave this empty and yaz will describe the changes for you.
vcs-committed = Saved version { $id }
vcs-nothing-to-commit = Nothing has changed since the last version.
vcs-restore = Restore this version
vcs-restored = Restored { $id }. Save a version to keep it.
vcs-empty = No versions recorded yet.
vcs-uncommitted = You have unsaved changes.
vcs-off-explains = Switch version control on to keep a history of this project.
vcs-error-unavailable = That version control system is not installed.
vcs-error-not-initialised = This project is not under version control.
vcs-error-would-lose-changes = Save a version first — restoring would overwrite changes that are not recorded anywhere.
vcs-error-not-implemented = That version control system is not built yet.
vcs-error-tool = Version control reported a problem.
vcs-error-io = A file could not be read or written.
vcs-error-unknown-backend = Unknown version control system.
workspace-tab-history = History

## Rich text and outline

menu-view-rich-text = Preview
workspace-tab-outline = Outline
outline-empty = No headings yet. Add a \section to see the document's structure.
outline-untitled = Untitled section

## The marks that bound the text

editor-text-start = Start of the text
editor-text-end = End of the text
editor-wrapper-show = Show the LaTeX around the text
editor-wrapper-hide = Hide the LaTeX around the text

## Views and line numbering

view-mode-rich = Preview
view-mode-source = Source
view-mode-show-rich = Show the document as it will read
view-mode-show-source = Show the source
menu-view-line-numbers = Line numbers
menu-view-line-numbers-off = None
menu-view-line-numbers-absolute = Absolute
menu-view-line-numbers-relative = Relative

## The file list

menu-view-files = File list
files-pin = Keep the file list open
files-unpin = Let the file list collapse

## Following the PDF back to the source

synctex-outside-project = That came from { $path }, which is outside this project.

## Appearance

settings-theme-help = A theme provides both light and dark.
settings-interface-locale-help = The document's own language is a project setting, set separately.
settings-appearance-build = Build a theme
settings-appearance-build-help = Start from the theme you are using and change what you like.
settings-appearance-build-open = Build theme…
settings-appearance-install = Install a theme…
theme-error-manifest = That folder does not contain a theme.
theme-error-modes = A theme has to provide both light and dark.
theme-installed = Installed { $name }.
theme-exported = Written to { $path }.

## The theme builder

theme-builder-title = Theme builder
theme-builder-name = Name
theme-builder-author = Author
theme-builder-mode-light = Light
theme-builder-mode-dark = Dark
theme-builder-editing = Editing the { $mode } palette. The window shows it as you go.
theme-builder-apply = Use this theme
theme-builder-export = Export…
theme-builder-reset = Start over
theme-builder-close = Close
theme-group-surfaces = Surfaces
theme-group-text = Text
theme-group-accent = Accent
theme-group-state = State
theme-group-borders = Borders
theme-group-editor = Editor
theme-group-syntax = Syntax highlighting
theme-group-pdf = PDF viewer
theme-token-bg-primary = Background
theme-token-bg-secondary = Panels
theme-token-bg-tertiary = Raised surfaces
theme-token-bg-overlay = Dialogs
theme-token-text-primary = Text
theme-token-text-secondary = Secondary text
theme-token-text-muted = Muted text
theme-token-accent = Accent
theme-token-accent-hover = Accent, hovered
theme-token-text-on-accent = Text on accent
theme-token-success = Success
theme-token-warning = Warning
theme-token-error = Error
theme-token-border = Borders
theme-token-border-strong = Strong borders
theme-token-editor-bg = Editor background
theme-token-editor-gutter-bg = Gutter
theme-token-editor-cursor = Cursor
theme-token-syntax-command = Commands
theme-token-syntax-environment = Environments
theme-token-syntax-math = Mathematics
theme-token-syntax-comment = Comments
theme-token-syntax-string = Strings
theme-token-syntax-reference = References
theme-token-pdf-bg = Page surround

## Formatting

format-bold = Bold
format-italic = Italic
format-underline = Underline
format-monospace = Monospace
format-small-caps = Small capitals
format-quote = Quotation
format-heading-1 = Heading 1
format-heading-2 = Heading 2
format-heading-3 = Heading 3
format-clear = Clear formatting

## Keyboard

settings-section-keys = Keyboard
keys-suites = Groups
keys-suite-core = Essentials
keys-suite-core-help = Save, find, complete. These cannot be switched off.
keys-suite-yaz = yaz
keys-suite-yaz-help = Everything behind Ctrl+Space: views, compiling, versions.
keys-suite-word = Word
keys-suite-word-help = What someone arriving from a word processor already knows.
keys-suite-lists = Lists
keys-suite-lists-help = Enter starts the next item, Tab makes it a sub-item.
keys-list-continue = Next list item
keys-list-indent = Make it a sub-item
keys-list-outdent = Lift it out one level
keys-complete = Suggest a completion
keys-press = Press the keys…
keys-unbound = Not bound
keys-reset = Put it back
keys-conflict = Another shortcut uses these keys.
menu-view-plain = Plain
menu-view-continuous = Continuous
menu-view-page = Page

## More heading colours

theme-group-headings = Headings
theme-token-heading-0 = Part
theme-token-heading-1 = Chapter
theme-token-heading-2 = Section
theme-token-heading-3 = Subsection
theme-token-heading-4 = Sub-subsection

## The ribbon

ribbon-title = Ribbon
ribbon-layout = Layout
ribbon-document = Document
ribbon-work = Work
ribbon-page-setup = Page setup
ribbon-paper = Format
ribbon-orientation = Orientation
orientation-portrait = Portrait
orientation-landscape = Landscape
ribbon-view = View
ribbon-vertical = Down the side
ribbon-title-block = Title block
ribbon-doc-title = Title
ribbon-doc-author = Author
ribbon-doc-date = Date
ribbon-doc-date-today = Today

paper-a4paper = A4
paper-a5paper = A5
paper-letterpaper = Letter
paper-legalpaper = Legal
paper-b5paper = B5

language-english = English
language-german = German
language-french = French
language-spanish = Spanish
language-italian = Italian

## The title bar

titlebar-autosave-on = Saving by itself
titlebar-autosave-off = Save by itself
titlebar-search = Search
titlebar-account = Account

## The status bar

status-page = Page { $page } of { $pages }
status-words = { $words } words (estimated)
status-zoom = Zoom
status-zoom-set = Set the zoom level
status-view = How the text is set
status-language-unset = No language set

menu-view-wrap = Wrap long lines
menu-view-comments = Comments
menu-view-line-breaks = Explicit line breaks
menu-view-machinery = Document machinery
menu-view-lock-tables = Keep tables drawn
menu-view-paper = White paper

## Ribbon command groups

group-project = Project
group-document = Document
group-history = History
group-find = Find
group-preferences = Preferences
group-views = Views
group-panes = Panes
group-editing = Editing
group-connections = Connections
group-versions = Versions
group-learn = Learn
group-about = About

## The reshaped ribbon

ribbon-start = Start
ribbon-connections = Connections
connections-zotero-group = Zotero
connections-obsidian-group = Obsidian

date-today = The day it is compiled
date-on = A particular day
date-none = No date

compile-clean = Compile from scratch
compile-choose-engine = Compile with…
compile-open-log = Open the log

ribbon-compact = Compact ribbon

## The file list

files-show-hidden = Hidden folders
files-show-other = Other file types
files-show-build = Build files
files-dim-build = Dim build files
files-expand = Open { $name }
files-collapse = Close { $name }
group-files = Files

## Editing a document that lives in several files

menu-view-joined = Joined document
joined-entered = Editing { $count } files as one document. Saving writes each of them.
joined-missing = Editing { $count } files as one document. These could not be read and are shown as commands: { $missing }
joined-refused = That edit runs from one file into the next, so there is no one file to write it to. Edit inside one of them.
joined-left = { $file } is not part of the document, so the joined view is off.
joined-save-failed = { $file } could not be saved: { $error }
joined-unexpanded = Not shown, could not be read: { $missing }
joined-drifted = The joined document no longer matches its files, so edits are not being written. Switch the joined view off to go back to one file.

## Generated lists, drawn from what the document says about itself

listing-contents = Contents
listing-figures = Figures
listing-tables = Tables
listing-glossary = Glossary
listing-bibliography = Bibliography
listing-index = Index
listing-compiled = Produced when the document is compiled.
listing-open-contents = Show the contents in the outline
listing-open-figures = Show the figures
listing-open-tables = Show the tables
listing-open-glossary = Show the glossary
listing-open-bibliography = Show the bibliography
listing-open-index = Show the index
pagebreak-clearpage = Page break
pagebreak-cleardoublepage = Page break, to a right-hand page
pagebreak-newpage = Page break
pagebreak-pagebreak = Page break

## References, citations and glossary entries, drawn as what they mean

reference-kind-heading = Section
reference-kind-figure = Figure
reference-kind-table = Table
reference-kind-equation = Equation
reference-kind-unknown = Reference
reference-undefined = Nothing in this document is labelled { $key }.
citation-unknown = { $key } is not in the bibliography that has been read.
glossary-unknown = { $key } is not defined in the glossary.
heading-label = Labelled { $label }
figure-caption-figure = Figure { $number }
figure-caption-table = Table { $number }

## Text formats

settings-section-formats = Formats
settings-group-formats = Text formats
settings-formats-help = Every text file opens with line numbers, wrapping, Vim and search. A format adds highlighting and its own conveniences on top; switching one off leaves the plain editor rather than nothing.
format-latex = LaTeX
format-markdown = Markdown
format-toml = TOML
format-yaml = YAML
format-bibtex = BibTeX
format-text = Plain text

## The Obsidian plugin

obsidian-command-insert-note = Insert note from vault
obsidian-pick-note = Choose a note
obsidian-pick-note-filter = Search your vault…
obsidian-no-notes = No notes found. Check the vault location in Connections.

## The Learn plugin

learn-command-capture = Capture element as an image
learn-command-clip = Capture element as a clip
learn-pick-name = Name the capture
learn-capturing = Capturing…
learn-captured = Saved to { $path }
learn-failed = The capture failed: { $error }

# Reading a value out of settings, and choosing a directory.
copy-action = Copy
copy-done = Copied
copy-show = Show
copy-hide = Hide
path-choose = Choose…
path-clear = Clear

# The plugins panel: what is installed, what is being written, and MCP.
settings-section-plugins = Plugins
plugins-installed = Installed
plugins-none = No plugins are loaded.
plugins-update-label = Updates
plugins-update-action = Check for updates
plugins-update-checking = Checking…
plugins-update-help = Each plugin says where its releases come from. yaz asks there.
plugins-update-none = This plugin does not take updates.
plugins-update-current = Up to date at { $version }.
plugins-update-available = Version { $version } is available.
plugins-update-unknown = No release found.
plugins-update-unreachable = Could not reach the repository.
plugins-development = Development
plugins-development-directory = Plugin directory
plugins-development-none = None chosen
plugins-development-help = A plugin you are working on, loaded from disk instead of from a release.
mcp-title = Model Context Protocol
mcp-enabled = Let an agent drive yaz
mcp-enabled-help = Listens on this machine only, and only for a client that sends the token.
mcp-address = Address
mcp-address-help = Put this in your agent's MCP configuration.
mcp-token = Token
mcp-token-help = The whole of the authentication. Treat it like a password.
mcp-not-running = Not running
mcp-tools = { $count } tools are reachable.

# Changing a table's shape from the preview.
table-column-add = Add a column after this one
table-column-remove = Remove this column
table-column-width = Drag to set this column's width
table-row-add = Add a row below this one
table-row-remove = Remove this row
table-row-height = Drag to set the space after this row

## The LaTeX packages plugin's glossary tab.

latex-packages-glossary-title = Glossary
latex-packages-glossary-empty = This document defines no glossary entries.
latex-packages-glossary-no-document = Open a document to see its glossary.
